// <auto-generated />
namespace DAL2try.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class resultpts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resultpts));
        
        string IMigrationMetadata.Id
        {
            get { return "201607311913543_resultpts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
